// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClH-Fv8QtyYVtByZ3yd1E8NroHgq9xDhs',
    appId: '1:126087561002:web:2aed1883808534ae9a2853',
    messagingSenderId: '126087561002',
    projectId: 'ic17-ec2c8',
    authDomain: 'ic17-ec2c8.firebaseapp.com',
    storageBucket: 'ic17-ec2c8.firebasestorage.app',
    measurementId: 'G-XQ6PW8LMJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwnTiZyvlZz5iBTNrj5lclkgVmqxvvzJk',
    appId: '1:126087561002:android:476c5288282732639a2853',
    messagingSenderId: '126087561002',
    projectId: 'ic17-ec2c8',
    storageBucket: 'ic17-ec2c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF2WvYdYicebfmguHOCDAWvx8xpkyuQ1A',
    appId: '1:126087561002:ios:4f7945891ffdb0a79a2853',
    messagingSenderId: '126087561002',
    projectId: 'ic17-ec2c8',
    storageBucket: 'ic17-ec2c8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseMessageing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF2WvYdYicebfmguHOCDAWvx8xpkyuQ1A',
    appId: '1:126087561002:ios:4f7945891ffdb0a79a2853',
    messagingSenderId: '126087561002',
    projectId: 'ic17-ec2c8',
    storageBucket: 'ic17-ec2c8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseMessageing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClH-Fv8QtyYVtByZ3yd1E8NroHgq9xDhs',
    appId: '1:126087561002:web:bd4874138db47f5a9a2853',
    messagingSenderId: '126087561002',
    projectId: 'ic17-ec2c8',
    authDomain: 'ic17-ec2c8.firebaseapp.com',
    storageBucket: 'ic17-ec2c8.firebasestorage.app',
    measurementId: 'G-QE898XQ49L',
  );
}
